name: Regression

on:
  workflow_dispatch:

jobs:
  run-smoke-test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest  --env qa --html=report.html -m page

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
            name: report
            path: report.html

      - name: Check if report.html exists
        run: ls -la report.html



      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v4
        with:
          html_file: '/report.html'
          job_summary: true
